### PR TITLE
Improve distribution-specific variable loading, fix metadata typo

### PR DESCRIPTION
**Pull request by virtualtam**
Hi @timorunge, and thanks for maintaining this Ansible role!

This PR improves distribution-specific variable loading by providing a default file for the Debian family, that can be overridden if need be (e.g. for non-LTS Ubuntu releases).

---

Only override variables for distribution-specific cases

Added:
- default variables for the Debian family

Removed:
- variable files that use Debian family defaults

### CODE REVIEW

**Comment by virtualtam** [comment]
Tests seem to be failing due to newly introduced rules in https://github.com/ansible/galaxy-lint-rules/pull/6 , let me know if I should update the PR to include fixes (or address them in a separate PR).

**Comment by timorunge** [comment]
Thank you virtualtam.
Currently I’ve just very limited access and no computer with me. It would be great if you can take care of the new limiting rules as well. I’ll take a look and merge once I’m back. :)

**Comment by virtualtam** [comment]
Sure,

The linter currently raises the following errors/warnings:
- `[E701GAL] Role info should contain company`
- `[E704GAL] Expected 'license' to be a valid SPDX license ID, instead found 'BSD'`
- `[E405GAL] Template files should have the extension '.j2'`
- `[E503] Tasks that run when changed should likely be handlers` (tasks/config/proxysql_global_variables.yml)

The corresponding changes would be:
- E701GAL: add your contact information as the company field
- E704GAL: update metadata and add a LICENSE file for either:
    - [BSD-2-Clause](https://spdx.org/licenses/BSD-2-Clause.html)
    - [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html)
- E405GAL: rename templates to use the Jinja2 extension
- E503: rewrite the `Check for global variable change` task as a handler

Just let me know if you are OK with these suggestions, and which license to opt for, and I'll update the PR :)

**Comment by timorunge** [comment]
Hey @virtualtam, 

sorry for the late reply, internet was cut off completely... :)

I've sorted (locally):

* E701GAL
* E704GAL

E405GAL is not super easy to fix and I'm wondering why it's failing since we're using a variable which is using the correct naming (https://github.com/timorunge/ansible-proxysql/blob/master/tasks/config.yml#L9 & https://github.com/timorunge/ansible-proxysql/blob/master/defaults/main.yml#L32). I'm anyways wondering why this is failing now since it was never a problem before. 

E503 ... Do you have an idea about a proper implementation?

**Comment by virtualtam** [comment]
Hey @timorunge, thanks for merging this PR (and sorry as well for the super late reply)!

I came to the same conclusion regarding `galaxy-lint-rules`, i.e. the linter currently lacks flexibility when it comes to variables and dynamically loaded variable files... Maybe it'd be worth disabling these specific warnings?

It's also worth noting that the project has been archived - https://github.com/ansible/galaxy-lint-rules/commit/c2b55358b2384d286c3f4121ac810bf4483cb4c4 , I guess its contents are being / will be upstreamed to [ansible-lint](https://github.com/ansible/ansible-lint) ([roadmap](https://github.com/ansible/ansible-lint/blob/master/ROADMAP.md))

**Pull request merged**
